; Comandos SO -> SPX_ENABLED=1 SPX_REPORT=full SPX_AUTO_START=1 php test.php

; -- PHP-SPX --
spx.http_enabled=1 
spx.http_key = "dev"
spx.http_ip_whitelist = "127.0.0.1,::1"
; Onde olhar -> http://localhost:8000/?SPX_KEY=dev&SPX_UI_URI=/

; -- XDEBUG --
xdebug.mode=profile 
xdebug.start_with_request=yes